/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Citizen {
    id: string;
    dob: Time;
    claims: bigint;
    accountStatus: AccountStatus;
    aadhaarStatus: AadhaarStatus;
    scheme: string;
    name: string;
    lastClaim?: Time;
    gender: Gender;
    photo?: ExternalBlob;
    amount: bigint;
    maritalStatus: MaritalStatus;
}
export interface Transaction {
    id: string;
    status: ClaimStatus;
    scheme: string;
    citizenId: string;
    timestamp: Time;
    amount: bigint;
}
export interface InputCitizen {
    id: string;
    dob: Time;
    accountStatus: AccountStatus;
    aadhaarStatus: AadhaarStatus;
    scheme: string;
    name: string;
    gender: Gender;
    photo?: ExternalBlob;
    amount: bigint;
    maritalStatus: MaritalStatus;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum AadhaarStatus {
    linked = "linked",
    unlinked = "unlinked"
}
export enum AccountStatus {
    active = "active",
    inactive = "inactive"
}
export enum ClaimStatus {
    denied = "denied",
    approved = "approved"
}
export enum Gender {
    other = "other",
    female = "female",
    male = "male"
}
export enum MaritalStatus {
    widowed = "widowed",
    married = "married",
    single = "single",
    divorced = "divorced"
}
export enum SystemStatus {
    active = "active",
    frozen = "frozen",
    paused = "paused"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addCitizen(input: InputCitizen): Promise<void>;
    addCitizens(batch: Array<InputCitizen>): Promise<void>;
    claimBenefits(id: string, scheme: string, amount: bigint): Promise<string>;
    countCitizens(): Promise<bigint>;
    countTransactions(): Promise<bigint>;
    deleteAllInactiveCitizens(): Promise<void>;
    getAllCitizens(): Promise<Array<Citizen>>;
    getBudget(): Promise<bigint>;
    getCitizen(id: string): Promise<Citizen | null>;
    getSystemStatus(): Promise<SystemStatus>;
    getTotalDisbursed(): Promise<bigint>;
    getTransactions(): Promise<Array<Transaction>>;
    resetBudget(amount: bigint): Promise<void>;
    setSystemStatus(status: SystemStatus): Promise<void>;
    updateAadhaarStatus(id: string, status: AadhaarStatus): Promise<void>;
}
import type { AadhaarStatus as _AadhaarStatus, AccountStatus as _AccountStatus, Citizen as _Citizen, ClaimStatus as _ClaimStatus, ExternalBlob as _ExternalBlob, Gender as _Gender, InputCitizen as _InputCitizen, MaritalStatus as _MaritalStatus, SystemStatus as _SystemStatus, Time as _Time, Transaction as _Transaction, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addCitizen(arg0: InputCitizen): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCitizen(await to_candid_InputCitizen_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCitizen(await to_candid_InputCitizen_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addCitizens(arg0: Array<InputCitizen>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCitizens(await to_candid_vec_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCitizens(await to_candid_vec_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async claimBenefits(arg0: string, arg1: string, arg2: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.claimBenefits(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimBenefits(arg0, arg1, arg2);
            return result;
        }
    }
    async countCitizens(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.countCitizens();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.countCitizens();
            return result;
        }
    }
    async countTransactions(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.countTransactions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.countTransactions();
            return result;
        }
    }
    async deleteAllInactiveCitizens(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllInactiveCitizens();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllInactiveCitizens();
            return result;
        }
    }
    async getAllCitizens(): Promise<Array<Citizen>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCitizens();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCitizens();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBudget(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getBudget();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBudget();
            return result;
        }
    }
    async getCitizen(arg0: string): Promise<Citizen | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCitizen(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCitizen(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSystemStatus(): Promise<SystemStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getSystemStatus();
                return from_candid_SystemStatus_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSystemStatus();
            return from_candid_SystemStatus_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalDisbursed(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalDisbursed();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalDisbursed();
            return result;
        }
    }
    async getTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactions();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactions();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async resetBudget(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetBudget(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetBudget(arg0);
            return result;
        }
    }
    async setSystemStatus(arg0: SystemStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSystemStatus(to_candid_SystemStatus_n42(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSystemStatus(to_candid_SystemStatus_n42(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateAadhaarStatus(arg0: string, arg1: AadhaarStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAadhaarStatus(arg0, to_candid_AadhaarStatus_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAadhaarStatus(arg0, to_candid_AadhaarStatus_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_AadhaarStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AadhaarStatus): AadhaarStatus {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_AccountStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccountStatus): AccountStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
async function from_candid_Citizen_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Citizen): Promise<Citizen> {
    return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_ClaimStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClaimStatus): ClaimStatus {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Gender_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_MaritalStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MaritalStatus): MaritalStatus {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_SystemStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SystemStatus): SystemStatus {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n31(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Citizen]): Promise<Citizen | null> {
    return value.length === 0 ? null : await from_candid_Citizen_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    dob: _Time;
    claims: bigint;
    accountStatus: _AccountStatus;
    aadhaarStatus: _AadhaarStatus;
    scheme: string;
    name: string;
    lastClaim: [] | [_Time];
    gender: _Gender;
    photo: [] | [_ExternalBlob];
    amount: bigint;
    maritalStatus: _MaritalStatus;
}): Promise<{
    id: string;
    dob: Time;
    claims: bigint;
    accountStatus: AccountStatus;
    aadhaarStatus: AadhaarStatus;
    scheme: string;
    name: string;
    lastClaim?: Time;
    gender: Gender;
    photo?: ExternalBlob;
    amount: bigint;
    maritalStatus: MaritalStatus;
}> {
    return {
        id: value.id,
        dob: value.dob,
        claims: value.claims,
        accountStatus: from_candid_AccountStatus_n23(_uploadFile, _downloadFile, value.accountStatus),
        aadhaarStatus: from_candid_AadhaarStatus_n25(_uploadFile, _downloadFile, value.aadhaarStatus),
        scheme: value.scheme,
        name: value.name,
        lastClaim: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.lastClaim)),
        gender: from_candid_Gender_n28(_uploadFile, _downloadFile, value.gender),
        photo: record_opt_to_undefined(await from_candid_opt_n30(_uploadFile, _downloadFile, value.photo)),
        amount: value.amount,
        maritalStatus: from_candid_MaritalStatus_n32(_uploadFile, _downloadFile, value.maritalStatus)
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _ClaimStatus;
    scheme: string;
    citizenId: string;
    timestamp: _Time;
    amount: bigint;
}): {
    id: string;
    status: ClaimStatus;
    scheme: string;
    citizenId: string;
    timestamp: Time;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_ClaimStatus_n40(_uploadFile, _downloadFile, value.status),
        scheme: value.scheme,
        citizenId: value.citizenId,
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
}): AccountStatus {
    return "active" in value ? AccountStatus.active : "inactive" in value ? AccountStatus.inactive : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    linked: null;
} | {
    unlinked: null;
}): AadhaarStatus {
    return "linked" in value ? AadhaarStatus.linked : "unlinked" in value ? AadhaarStatus.unlinked : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    female: null;
} | {
    male: null;
}): Gender {
    return "other" in value ? Gender.other : "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    widowed: null;
} | {
    married: null;
} | {
    single: null;
} | {
    divorced: null;
}): MaritalStatus {
    return "widowed" in value ? MaritalStatus.widowed : "married" in value ? MaritalStatus.married : "single" in value ? MaritalStatus.single : "divorced" in value ? MaritalStatus.divorced : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    frozen: null;
} | {
    paused: null;
}): SystemStatus {
    return "active" in value ? SystemStatus.active : "frozen" in value ? SystemStatus.frozen : "paused" in value ? SystemStatus.paused : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    denied: null;
} | {
    approved: null;
}): ClaimStatus {
    return "denied" in value ? ClaimStatus.denied : "approved" in value ? ClaimStatus.approved : value;
}
async function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Citizen>): Promise<Array<Citizen>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Citizen_n21(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n38(_uploadFile, _downloadFile, x));
}
function to_candid_AadhaarStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AadhaarStatus): _AadhaarStatus {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_AccountStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccountStatus): _AccountStatus {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Gender_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
async function to_candid_InputCitizen_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InputCitizen): Promise<_InputCitizen> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_MaritalStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MaritalStatus): _MaritalStatus {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_SystemStatus_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SystemStatus): _SystemStatus {
    return to_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    dob: Time;
    accountStatus: AccountStatus;
    aadhaarStatus: AadhaarStatus;
    scheme: string;
    name: string;
    gender: Gender;
    photo?: ExternalBlob;
    amount: bigint;
    maritalStatus: MaritalStatus;
}): Promise<{
    id: string;
    dob: _Time;
    accountStatus: _AccountStatus;
    aadhaarStatus: _AadhaarStatus;
    scheme: string;
    name: string;
    gender: _Gender;
    photo: [] | [_ExternalBlob];
    amount: bigint;
    maritalStatus: _MaritalStatus;
}> {
    return {
        id: value.id,
        dob: value.dob,
        accountStatus: to_candid_AccountStatus_n10(_uploadFile, _downloadFile, value.accountStatus),
        aadhaarStatus: to_candid_AadhaarStatus_n12(_uploadFile, _downloadFile, value.aadhaarStatus),
        scheme: value.scheme,
        name: value.name,
        gender: to_candid_Gender_n14(_uploadFile, _downloadFile, value.gender),
        photo: value.photo ? candid_some(await to_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.photo)) : candid_none(),
        amount: value.amount,
        maritalStatus: to_candid_MaritalStatus_n17(_uploadFile, _downloadFile, value.maritalStatus)
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccountStatus): {
    active: null;
} | {
    inactive: null;
} {
    return value == AccountStatus.active ? {
        active: null
    } : value == AccountStatus.inactive ? {
        inactive: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AadhaarStatus): {
    linked: null;
} | {
    unlinked: null;
} {
    return value == AadhaarStatus.linked ? {
        linked: null
    } : value == AadhaarStatus.unlinked ? {
        unlinked: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    other: null;
} | {
    female: null;
} | {
    male: null;
} {
    return value == Gender.other ? {
        other: null
    } : value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MaritalStatus): {
    widowed: null;
} | {
    married: null;
} | {
    single: null;
} | {
    divorced: null;
} {
    return value == MaritalStatus.widowed ? {
        widowed: null
    } : value == MaritalStatus.married ? {
        married: null
    } : value == MaritalStatus.single ? {
        single: null
    } : value == MaritalStatus.divorced ? {
        divorced: null
    } : value;
}
function to_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SystemStatus): {
    active: null;
} | {
    frozen: null;
} | {
    paused: null;
} {
    return value == SystemStatus.active ? {
        active: null
    } : value == SystemStatus.frozen ? {
        frozen: null
    } : value == SystemStatus.paused ? {
        paused: null
    } : value;
}
async function to_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<InputCitizen>): Promise<Array<_InputCitizen>> {
    return await Promise.all(value.map(async (x)=>await to_candid_InputCitizen_n8(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
