 

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AadhaarStatus = { 'linked' : null } |
  { 'unlinked' : null };
export type AccountStatus = { 'active' : null } |
  { 'inactive' : null };
export interface Citizen {
  'id' : string,
  'dob' : Time,
  'claims' : bigint,
  'accountStatus' : AccountStatus,
  'aadhaarStatus' : AadhaarStatus,
  'scheme' : string,
  'name' : string,
  'lastClaim' : [] | [Time],
  'gender' : Gender,
  'photo' : [] | [ExternalBlob],
  'amount' : bigint,
  'maritalStatus' : MaritalStatus,
}
export type ClaimStatus = { 'denied' : null } |
  { 'approved' : null };
export type ExternalBlob = Uint8Array;
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export interface InputCitizen {
  'id' : string,
  'dob' : Time,
  'scheme' : string,
  'name' : string,
  'gender' : Gender,
  'photo' : [] | [ExternalBlob],
  'amount' : bigint,
  'maritalStatus' : MaritalStatus,
}
export type MaritalStatus = { 'widowed' : null } |
  { 'married' : null } |
  { 'single' : null } |
  { 'divorced' : null };
export type SystemStatus = { 'active' : null } |
  { 'frozen' : null } |
  { 'paused' : null };
export type Time = bigint;
export interface Transaction {
  'id' : string,
  'status' : ClaimStatus,
  'scheme' : string,
  'citizenId' : string,
  'timestamp' : Time,
  'amount' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addCitizen' : ActorMethod<[InputCitizen], undefined>,
  'addCitizens' : ActorMethod<[Array<InputCitizen>], undefined>,
  'claimBenefits' : ActorMethod<[string, string, bigint], string>,
  'countCitizens' : ActorMethod<[], bigint>,
  'countTransactions' : ActorMethod<[], bigint>,
  'deleteAllInactiveCitizens' : ActorMethod<[], undefined>,
  'getAllCitizens' : ActorMethod<[], Array<Citizen>>,
  'getBudget' : ActorMethod<[], bigint>,
  'getCitizen' : ActorMethod<[string], [] | [Citizen]>,
  'getSystemStatus' : ActorMethod<[], SystemStatus>,
  'getTotalDisbursed' : ActorMethod<[], bigint>,
  'getTransactions' : ActorMethod<[], Array<Transaction>>,
  'resetBudget' : ActorMethod<[bigint], undefined>,
  'setSystemStatus' : ActorMethod<[SystemStatus], undefined>,
  'updateAadhaarStatus' : ActorMethod<[string, AadhaarStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];