 

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MaritalStatus = IDL.Variant({
  'widowed' : IDL.Null,
  'married' : IDL.Null,
  'single' : IDL.Null,
  'divorced' : IDL.Null,
});
export const InputCitizen = IDL.Record({
  'id' : IDL.Text,
  'dob' : Time,
  'scheme' : IDL.Text,
  'name' : IDL.Text,
  'gender' : Gender,
  'photo' : IDL.Opt(ExternalBlob),
  'amount' : IDL.Int,
  'maritalStatus' : MaritalStatus,
});
export const AccountStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const AadhaarStatus = IDL.Variant({
  'linked' : IDL.Null,
  'unlinked' : IDL.Null,
});
export const Citizen = IDL.Record({
  'id' : IDL.Text,
  'dob' : Time,
  'claims' : IDL.Int,
  'accountStatus' : AccountStatus,
  'aadhaarStatus' : AadhaarStatus,
  'scheme' : IDL.Text,
  'name' : IDL.Text,
  'lastClaim' : IDL.Opt(Time),
  'gender' : Gender,
  'photo' : IDL.Opt(ExternalBlob),
  'amount' : IDL.Int,
  'maritalStatus' : MaritalStatus,
});
export const SystemStatus = IDL.Variant({
  'active' : IDL.Null,
  'frozen' : IDL.Null,
  'paused' : IDL.Null,
});
export const ClaimStatus = IDL.Variant({
  'denied' : IDL.Null,
  'approved' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'status' : ClaimStatus,
  'scheme' : IDL.Text,
  'citizenId' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addCitizen' : IDL.Func([InputCitizen], [], []),
  'addCitizens' : IDL.Func([IDL.Vec(InputCitizen)], [], []),
  'claimBenefits' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [IDL.Text], []),
  'countCitizens' : IDL.Func([], [IDL.Nat], ['query']),
  'countTransactions' : IDL.Func([], [IDL.Nat], ['query']),
  'deleteAllInactiveCitizens' : IDL.Func([], [], []),
  'getAllCitizens' : IDL.Func([], [IDL.Vec(Citizen)], ['query']),
  'getBudget' : IDL.Func([], [IDL.Int], ['query']),
  'getCitizen' : IDL.Func([IDL.Text], [IDL.Opt(Citizen)], ['query']),
  'getSystemStatus' : IDL.Func([], [SystemStatus], ['query']),
  'getTotalDisbursed' : IDL.Func([], [IDL.Int], ['query']),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'resetBudget' : IDL.Func([IDL.Int], [], []),
  'setSystemStatus' : IDL.Func([SystemStatus], [], []),
  'updateAadhaarStatus' : IDL.Func([IDL.Text, AadhaarStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MaritalStatus = IDL.Variant({
    'widowed' : IDL.Null,
    'married' : IDL.Null,
    'single' : IDL.Null,
    'divorced' : IDL.Null,
  });
  const InputCitizen = IDL.Record({
    'id' : IDL.Text,
    'dob' : Time,
    'scheme' : IDL.Text,
    'name' : IDL.Text,
    'gender' : Gender,
    'photo' : IDL.Opt(ExternalBlob),
    'amount' : IDL.Int,
    'maritalStatus' : MaritalStatus,
  });
  const AccountStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const AadhaarStatus = IDL.Variant({
    'linked' : IDL.Null,
    'unlinked' : IDL.Null,
  });
  const Citizen = IDL.Record({
    'id' : IDL.Text,
    'dob' : Time,
    'claims' : IDL.Int,
    'accountStatus' : AccountStatus,
    'aadhaarStatus' : AadhaarStatus,
    'scheme' : IDL.Text,
    'name' : IDL.Text,
    'lastClaim' : IDL.Opt(Time),
    'gender' : Gender,
    'photo' : IDL.Opt(ExternalBlob),
    'amount' : IDL.Int,
    'maritalStatus' : MaritalStatus,
  });
  const SystemStatus = IDL.Variant({
    'active' : IDL.Null,
    'frozen' : IDL.Null,
    'paused' : IDL.Null,
  });
  const ClaimStatus = IDL.Variant({
    'denied' : IDL.Null,
    'approved' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'status' : ClaimStatus,
    'scheme' : IDL.Text,
    'citizenId' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addCitizen' : IDL.Func([InputCitizen], [], []),
    'addCitizens' : IDL.Func([IDL.Vec(InputCitizen)], [], []),
    'claimBenefits' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [IDL.Text], []),
    'countCitizens' : IDL.Func([], [IDL.Nat], ['query']),
    'countTransactions' : IDL.Func([], [IDL.Nat], ['query']),
    'deleteAllInactiveCitizens' : IDL.Func([], [], []),
    'getAllCitizens' : IDL.Func([], [IDL.Vec(Citizen)], ['query']),
    'getBudget' : IDL.Func([], [IDL.Int], ['query']),
    'getCitizen' : IDL.Func([IDL.Text], [IDL.Opt(Citizen)], ['query']),
    'getSystemStatus' : IDL.Func([], [SystemStatus], ['query']),
    'getTotalDisbursed' : IDL.Func([], [IDL.Int], ['query']),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'resetBudget' : IDL.Func([IDL.Int], [], []),
    'setSystemStatus' : IDL.Func([SystemStatus], [], []),
    'updateAadhaarStatus' : IDL.Func([IDL.Text, AadhaarStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };